card_chk:
  start: |
    <b>âˆ ğ‘·ğ’ğ’†ğ’‚ğ’”ğ’† ğ‘¾ğ’‚ğ’Šğ’• âˆ
    âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘·ğ’“ğ’ğ’ˆğ’“ğ’†ğ’”ğ’” âª¢</b> <code>â—¯â—¯â—¯â—¯â—¯â—¯â—¯â—¯ 0%</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
  mid: |
    <b>âˆ ğ‘·ğ’ğ’†ğ’‚ğ’”ğ’† ğ‘¾ğ’‚ğ’Šğ’• âˆ
    âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘·ğ’“ğ’ğ’ˆğ’“ğ’†ğ’”ğ’” âª¢</b> <code>â¬¤â¬¤â—¯â—¯â—¯â—¯â—¯ 30%</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
  semi: |
    <b>âˆ ğ‘·ğ’ğ’†ğ’‚ğ’”ğ’† ğ‘¾ğ’‚ğ’Šğ’• âˆ
    âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘·ğ’“ğ’ğ’ˆğ’“ğ’†ğ’”ğ’” âª¢</b> <code>â¬¤â¬¤â¬¤â—¯â—¯â—¯ 60%</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
  semi_final: |
    <b>âˆ ğ‘·ğ’ğ’†ğ’‚ğ’”ğ’† ğ‘¾ğ’‚ğ’Šğ’• âˆ
    âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘·ğ’“ğ’ğ’ˆğ’“ğ’†ğ’”ğ’” âª¢</b> <code>â¬¤â¬¤â¬¤â¬¤â¬¤â¬¤â¬¤â—¯ 90%</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
  final: |
    <b>âˆ ğ‘ªğ’‚ğ’“ğ’… âª¢</b> <code>{lista}</code>
    <b>âˆ ğ‘ºğ’•ğ’‚ğ’•ğ’–ğ’” âª¢</b> <code>{status} {logo}</code>

    <b>âˆ ğ‘¹ğ’†ğ’”ğ’‘ğ’ğ’ğ’”ğ’† âª¢</b> <code>{respo}</code>
    <b>âˆ ğ‘©ğ’Šğ’ ğ‘«ğ’‚ğ’•ğ’‚ âª¢</b> <code>{vendor} - {type} - {country} - {flag}</code>
    <b>âˆ ğ‘©ğ’‚ğ’ğ’Œ ğ‘«ğ’‚ğ’•ğ’‚ âª¢</b> <code>{bank_name}</code>

    <b>âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
    <b>âˆ ğ‘ªğ’‰ğ’†ğ’„ğ’Œğ’†ğ’… ğ‘©ğ’š  âª¢</b> <a href="tg://user?id={id}">{name}</a> <code>[{role}]</code>
    <b>âˆ ğ˜½ğ™¤ğ™© ğ˜½ğ™®  âª¢</b> <a href="https://t.me/anidec4ypt3d">hidden</a>
  sp_final: |
    <b>âˆ ğ‘ªğ’‚ğ’“ğ’… âª¢</b> <code>{lista}</code>
    <b>âˆ ğ‘ºğ’•ğ’‚ğ’•ğ’–ğ’” âª¢</b> <code>{status} {logo}</code>
    <b>âˆ ğ‘ªğ‘½ğ‘½ âª¢</b> <code>{cvvs}</code> | <b>ğ‘¨ğ‘½ğ‘º âª¢</b> <code>{avs}</code>

    <b>âˆ ğ‘¹ğ’†ğ’”ğ’‘ğ’ğ’ğ’”ğ’† âª¢</b> <code>{respo}</code>
    <b>âˆ ğ‘©ğ’Šğ’ ğ‘«ğ’‚ğ’•ğ’‚ âª¢</b> <code>{vendor} - {type} - {country} - {flag}</code>
    <b>âˆ ğ‘©ğ’‚ğ’ğ’Œ ğ‘«ğ’‚ğ’•ğ’‚ âª¢</b> <code>{bank_name}</code>

    <b>âˆ ğ‘®ğ’‚ğ’•ğ’†ğ’˜ğ’‚ğ’š âª¢</b> <code>{gate_name}</code>
    <b>âˆ ğ‘»ğ’ğ’ğ’Œ  âª¢</b> <code>{taken}s</code>
    <b>âˆ ğ‘ªğ’‰ğ’†ğ’„ğ’Œğ’†ğ’… ğ‘©ğ’š  âª¢</b> <a href="tg://user?id={id}">{name}</a> <code>[{role}]</code>
    <b>âˆ ğ˜½ğ™¤ğ™© ğ˜½ğ™®  âª¢</b> <a href="https://t.me/anidec4ypt3d">hidden</a>


  antispam: |
     <b> AntiSpam try again after {time_left}'s</b>